In [1]:
import numpy as np
import cv2
import albumentations as A
from albumentations.pytorch import ToTensorV2
import random
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
RESIZE_WIDTH = 192
RESIZE_HEIGHT = 192

In [3]:
class CustomDarker(A.ImageOnlyTransform):
    def __init__(self, max_dark, max_bright, always_apply=False, p=0.5):
        super().__init__(always_apply=always_apply, p=p)  # Pass 'p' to parent
        self.max_dark = max_dark
        self.max_bright = max_bright

    def apply(self, image, **params):
        # Randomly choose a darkening factor between max_dark and max_bright
        factor = 1 + np.random.uniform(self.max_dark, self.max_bright)
        # Apply the factor to darken the image
        image = image * factor
        # Clip values to ensure they stay within valid range [0, 255]
        image = np.clip(image, 0, 255).astype(np.uint8)
        return image


In [ ]:
# Soft augmentation pipeline
augmentation_pipeline = A.Compose([
    A.Rotate(limit=10, border_mode=cv2.BORDER_REFLECT, p=1),
    A.RandomScale(scale_limit=0.1, p=0.2),
    A.OneOf([
        CustomDarker(max_dark=-0.4, max_bright=-0.1, p=0.5),
        CustomDarker(max_dark=-0.2, max_bright=0.0, p=0.25),
        A.RandomBrightnessContrast(brightness_limit=0.2, contrast_limit=0.2, p=0.25),
    ], p=0.5),
    A.OneOf([
        A.MotionBlur(blur_limit=3, p=0.4),
        A.GaussianBlur(blur_limit=(3, 5), p=0.4),
    ], p=0.2),
    A.ISONoise(p=0.15),
    A.Perspective(p=0.15),
    A.CoarseDropout(num_holes_range=(1, 1), hole_width_range=(16, 48), hole_height_range=(16, 48), p=0.2),
    A.Resize(width=RESIZE_WIDTH, height=RESIZE_HEIGHT, p=1.0),
    ToTensorV2()
])

In [ ]:
# Aggressive augmentation pipeline
augmentation_pipeline = A.Compose([
    A.Affine(scale=(0.8, 1.2), translate_percent=(0.1, 0.1), \
             rotate=(-30, 30),  border_mode=cv2.BORDER_CONSTANT, fit_output=False, p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, p=0.4),
    A.OneOf([
        A.MotionBlur(blur_limit=7, p=0.3),
        A.GaussianBlur(blur_limit=(3, 7), p=0.3),
    ], p=0.3),
    A.CoarseDropout(num_holes_range=(2, 4), hole_height_range=(32, 32),\
                     hole_width_range=(32, 32), p=0.15),
    A.Perspective(scale=(0.05, 0.15), p=0.3),
    A.RandomShadow(p=0.2),
    A.ISONoise(p=0.2),
    A.Sharpen(p=0.3),
    A.Resize(width=RESIZE_WIDTH, height=RESIZE_HEIGHT, p=1.0),
    ToTensorV2()
])


In [3]:
augmentation_pipeline = A.Compose([
    A.ToGray(p=1.0),
    A.Sharpen(alpha=(0.2, 0.5), p=0.7),  
    A.CLAHE(clip_limit=2.0, tile_grid_size=(8, 8), p=0.3),
    A.Affine(scale=(0.9, 1.1), translate_percent=(0.05, 0.05), rotate=(-15, 15), p=0.5),
    A.Perspective(scale=(0.05, 0.15), p=0.3),
    A.GaussianBlur(blur_limit=(3, 5), p=0.3),
    A.CoarseDropout(num_holes_range=(2, 4), hole_height_range=(16, 32),\
                    hole_width_range=(16, 32), p=0.2),
    A.Resize(width=RESIZE_WIDTH, height=RESIZE_HEIGHT),
    ToTensorV2()
])

In [4]:
def augment_image(image, num_augments=6):
    augmented_images = []
    for _ in range(num_augments):
        augmented = augmentation_pipeline(image=image)['image']
        augmented_images.append(augmented)

    return augmented_images

In [96]:
from matplotlib import gridspec

def preview_augment(image, num_augments=4):
    augmented_images = []
    for _ in range(num_augments):
        augmented = augmentation_pipeline(image=image)['image']
        augmented_images.append(augmented)
    
    return augmented_images

def get_and_preview_augmentation(dataset_path, class_name, sample_count=3):
    import matplotlib.pyplot as plt
    
    image_dir = f"{dataset_path}/{class_name}"
    preview_dir = f"preview_augmented/{class_name}"
    os.makedirs(preview_dir, exist_ok=True)
    
    # Get a list of all images in the directory
    image_files = [f for f in os.listdir(image_dir) if f.endswith('.jpg')]
    
    # Take a sample of the images
    if len(image_files) > sample_count:
        image_files = random.sample(image_files, sample_count)
    
    for idx, filename in enumerate(image_files):
        img_path = os.path.join(image_dir, filename)
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        # Resize for preview
        preview_image = cv2.resize(image, (RESIZE_WIDTH, RESIZE_HEIGHT))
        
        # Generate augmented versions
        augmented_images = preview_augment(preview_image, num_augments=4)
        
        # Create a figure for visualization
        fig = plt.figure(figsize=(15, 10))
        gs = gridspec.GridSpec(2, 3)
        
        # Display original image
        ax = plt.subplot(gs[0, 0])
        ax.imshow(preview_image)
        ax.set_title('Original')
        ax.axis('off')
        
        # Display augmented images
        for i, aug_img in enumerate(augmented_images):
            row, col = (i+1) // 3, (i+1) % 3
            ax = plt.subplot(gs[row, col])
            
            # Convert tensor to numpy if needed
            if hasattr(aug_img, 'permute'):
                aug_img = aug_img.permute(1, 2, 0).numpy()
                
            ax.imshow(aug_img)
            ax.set_title(f'Augmented {i+1}')
            ax.axis('off')
        
        # Save the figure
        output_path = os.path.join(preview_dir, f"{filename.split('.')[0]}_preview.png")
        plt.tight_layout()
        plt.savefig(output_path)
        plt.close()
        
        print(f"Saved preview for {filename} to {output_path}")
    
    print(f"Previews generated for {class_name} 🔥")

get_and_preview_augmentation("dataset", "minere", sample_count=5)


Saved preview for minere_196.jpg to preview_augmented/minere\minere_196_preview.png
Saved preview for minere_263.jpg to preview_augmented/minere\minere_263_preview.png
Saved preview for minere_65.jpg to preview_augmented/minere\minere_65_preview.png
Saved preview for minere_208.jpg to preview_augmented/minere\minere_208_preview.png
Saved preview for minere_124.jpg to preview_augmented/minere\minere_124_preview.png
Previews generated for minere 🔥


In [5]:
import os
import cv2
import asyncio
import psutil
from functools import partial

dataset_path = "dataset"
augmented_path = "augmented"
class_names = ["aura", "minere", "montfleur"]
MAX_WORKERS = min(8, psutil.cpu_count() + 2)
MEMORY_SAFE_MODE = True
CHUNK_SIZE = 2

print(f"⚙️  Config: Workers={MAX_WORKERS}, Chunk={CHUNK_SIZE}, SafeMode={MEMORY_SAFE_MODE}")

semaphore = asyncio.Semaphore(MAX_WORKERS)

async def memory_check():
    """Non-blocking memory monitor"""
    if MEMORY_SAFE_MODE and psutil.virtual_memory().percent > 75:
        print("💤 Memory buffer...")
        await asyncio.sleep(2)
        return True
    return False

def process_image_batch(img_path, num_augments):
    """Process image and return augmented images (let Python's GC handle cleanup)"""
    try:
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        augmented = augment_image(image, num_augments=num_augments)
        # No need to explicitly delete 'image'
        return augmented
    finally:
        cv2.waitKey(1)  # Release OpenCV hooks

async def augment_single_image(filename, image_dir, output_dir, idx_i, num_augments):
    async with semaphore:
        if await memory_check():
            await asyncio.sleep(1)

        img_path = os.path.join(image_dir, filename)
        print(f"📤 Loading {filename}...")
        
        # Process with memory limits
        augmented_images = await asyncio.to_thread(
            partial(process_image_batch, num_augments=num_augments),
            img_path
        )

        # Process in chunks
        write_tasks = []
        base_name = os.path.splitext(filename)[0].split('_')[0]
        
        for idx_j, aug in enumerate(augmented_images):
            if idx_j % CHUNK_SIZE == 0 and idx_j != 0:
                await asyncio.gather(*write_tasks)
                write_tasks.clear()
                await asyncio.sleep(0.2)
            
            output_path = os.path.join(output_dir, f"{base_name}_aug_{idx_i}_{idx_j}.jpg")
            aug_np = aug.permute(1, 2, 0).numpy()
            aug_bgr = cv2.cvtColor(aug_np, cv2.COLOR_RGB2BGR)
            
            write_tasks.append(
                asyncio.to_thread(cv2.imwrite, output_path, aug_bgr)
            )

        # Final flush of remaining tasks
        if write_tasks:
            await asyncio.gather(*write_tasks)

        # Let variables go out of scope naturally
        await asyncio.sleep(0.2)

async def process_augment_class(class_name):
    image_dir = os.path.join(dataset_path, class_name)
    output_dir = os.path.join(augmented_path, class_name)
    os.makedirs(output_dir, exist_ok=True)

    filenames = [f for f in os.listdir(image_dir) if f.endswith(".jpg")]
    print(f"🔥 Starting {class_name} ({len(filenames)} images)")

    # Process in smaller batches
    BATCH_SIZE = MAX_WORKERS * 1  # Reduced multiplier
    for batch_idx in range(0, len(filenames), BATCH_SIZE):
        batch = filenames[batch_idx:batch_idx+BATCH_SIZE]
        
        tasks = [
            augment_single_image(filename, image_dir, output_dir, idx_i, 8)
            for idx_i, filename in enumerate(batch, start=batch_idx)
        ]
        
        await asyncio.gather(*tasks)
        print(f"✅ Completed batch {batch_idx//BATCH_SIZE + 1}")
        await asyncio.sleep(1)

async def main():
    print("🚀 Starting SAFE augmentation...")
    await asyncio.gather(*[process_augment_class(cls) for cls in class_names])
    print("🎯 All done! PC survived! 🎉")

if __name__ == "__main__":
    import nest_asyncio
    nest_asyncio.apply()
    asyncio.run(main())


⚙️  Config: Workers=8, Chunk=2, SafeMode=True
🚀 Starting SAFE augmentation...
🔥 Starting aura (330 images)
🔥 Starting minere (330 images)
🔥 Starting montfleur (330 images)
📤 Loading aura_1.jpg...
📤 Loading aura_10.jpg...
📤 Loading aura_100.jpg...
📤 Loading aura_101.jpg...
📤 Loading aura_102.jpg...
📤 Loading aura_103.jpg...
📤 Loading aura_104.jpg...
📤 Loading aura_105.jpg...
📤 Loading minere_1.jpg...
📤 Loading minere_10.jpg...
📤 Loading minere_100.jpg...
📤 Loading minere_101.jpg...
📤 Loading minere_102.jpg...
📤 Loading minere_103.jpg...
📤 Loading minere_104.jpg...
📤 Loading minere_105.jpg...
✅ Completed batch 1
📤 Loading montfleur_1.jpg...
📤 Loading montfleur_10.jpg...
📤 Loading montfleur_100.jpg...
📤 Loading montfleur_101.jpg...
📤 Loading montfleur_102.jpg...
📤 Loading montfleur_103.jpg...
📤 Loading montfleur_104.jpg...
📤 Loading montfleur_105.jpg...
📤 Loading aura_106.jpg...
✅ Completed batch 1
📤 Loading aura_107.jpg...
📤 Loading aura_108.jpg...
📤 Loading aura_109.jpg...
📤 Loading aur

In [6]:
import gc
gc.collect()

16

In [7]:
import tensorflow as tf
import os
import random

def parse_image(image_path, label):
    img = tf.io.read_file(image_path)
    img = tf.image.decode_jpeg(img, channels=3)  # Decode image
    img = tf.image.resize(img, [RESIZE_HEIGHT, RESIZE_WIDTH])
    print(f"Resized image shape: {img.shape}")
    img = tf.image.convert_image_dtype(img, dtype=tf.float32)
    img = img / 255.0
    return img, label

def prepare_tf_dataset(data_dir="augmented", original_data_dir="original", batch_size=32, seed=42):
    # Process class directories for augmented and original data
    class_names = sorted(os.listdir(data_dir))
    print(f"Found {len(class_names)} classes: {class_names}")
    
    # Prepare augmented dataset (training)
    augmented_image_paths = []
    augmented_labels = []
    for class_idx, class_name in enumerate(class_names):
        class_dir = os.path.join(data_dir, class_name)
        image_paths = [os.path.join(class_dir, filename) 
                       for filename in os.listdir(class_dir) 
                       if filename.endswith('.jpg')]
        augmented_image_paths.extend(image_paths)
        augmented_labels.extend([class_idx] * len(image_paths))
    
    # Prepare original dataset (validation & test)
    original_image_paths = []
    original_labels = []
    for class_idx, class_name in enumerate(class_names):
        class_dir = os.path.join(original_data_dir, class_name)
        image_paths = [os.path.join(class_dir, filename) 
                       for filename in os.listdir(class_dir) 
                       if filename.endswith('.jpg')]
        original_image_paths.extend(image_paths)
        original_labels.extend([class_idx] * len(image_paths))
    
    # Shuffle augmented dataset (training)
    combined = list(zip(augmented_image_paths, augmented_labels))
    random.Random(seed).shuffle(combined)
    augmented_image_paths, augmented_labels = zip(*combined)

    # Shuffle original dataset (validation & test)
    combined_original = list(zip(original_image_paths, original_labels))
    random.Random(seed).shuffle(combined_original)
    original_image_paths, original_labels = zip(*combined_original)
    
    # Use all augmented images for training
    train_paths, train_labels = list(augmented_image_paths[:]), list(augmented_labels[:])
    
    # Fix constant length for validation and test
    start_idx = random.randint(0, 990 - 792 - 1)
    val_paths, val_labels = list(original_image_paths[start_idx:start_idx + 792]), list(original_labels[start_idx:start_idx + 792])

    start_idx = random.randint(0, 990 - 792 - 1)
    test_paths, test_labels = list(original_image_paths[start_idx:start_idx + 792]), list(original_labels[start_idx:start_idx + 792])

    # Create datasets
    train_dataset = tf.data.Dataset.from_tensor_slices((train_paths, train_labels))
    val_dataset = tf.data.Dataset.from_tensor_slices((val_paths, val_labels))
    test_dataset = tf.data.Dataset.from_tensor_slices((test_paths, test_labels))

    # Prepare datasets
    train_dataset = train_dataset.map(parse_image, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    train_dataset = train_dataset.shuffle(buffer_size=1024, seed=seed)
    train_dataset = train_dataset.batch(batch_size)
    train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)

    val_dataset = val_dataset.map(parse_image, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    val_dataset = val_dataset.shuffle(buffer_size=1024, seed=seed)
    val_dataset = val_dataset.batch(batch_size)
    val_dataset = val_dataset.prefetch(tf.data.experimental.AUTOTUNE)

    test_dataset = test_dataset.map(parse_image, num_parallel_calls=tf.data.experimental.AUTOTUNE)
    test_dataset = test_dataset.shuffle(buffer_size=1024, seed=seed)
    test_dataset = test_dataset.batch(batch_size)
    test_dataset = test_dataset.prefetch(tf.data.experimental.AUTOTUNE)

    print(f"Traing dataset: {len(train_paths)} images")
    print(f"Validation dataset: {len(val_paths)} images")
    print(f"Test dataset: {len(test_paths)} images")
    print("🔥 Datasets ready!")
    return train_dataset, val_dataset, test_dataset, class_names


In [8]:
import pandas as pd
import numpy as np

def print_dataset_examples(dataset, class_names):
    for images, labels in dataset.take(1):
        print(f"Image batch shape: {images.shape}")
        
        # Flatten the images to 1D arrays and create a DataFrame
        flattened_images = [image.numpy().flatten() for image in images]  # Flatten the images
        labels_as_strings = [class_names[label.numpy()] for label in labels]  # Convert labels to class names
        
        # Create a DataFrame
        df = pd.DataFrame(flattened_images)
        df['label'] = labels_as_strings  # Add class labels to the DataFrame
        
        # Display the DataFrame
        print("Dataset Examples (Flattened images and labels):")
        print(df.head())  # Display the first 5 rows of the DataFrame



In [12]:
BATCH_SIZE = 8
SEED = 42

train_dataset, val_dataset, test_dataset, class_names = prepare_tf_dataset(
    data_dir="augmented",
    original_data_dir="dataset",
    batch_size=BATCH_SIZE,
    seed=SEED
)


Found 3 classes: ['aura', 'minere', 'montfleur']
Resized image shape: (192, 192, 3)
Resized image shape: (192, 192, 3)
Resized image shape: (192, 192, 3)
Traing dataset: 7920 images
Validation dataset: 792 images
Test dataset: 792 images
🔥 Datasets ready!


In [13]:
for images, labels in train_dataset.take(5):  # `take(1)` will fetch just one batch
    for i in range(len(labels)):
        print(f"Image {i+1} - Label: {labels[i].numpy()}")

Image 1 - Label: 1
Image 2 - Label: 2
Image 3 - Label: 2
Image 4 - Label: 2
Image 5 - Label: 1
Image 6 - Label: 1
Image 7 - Label: 1
Image 8 - Label: 0
Image 1 - Label: 0
Image 2 - Label: 0
Image 3 - Label: 1
Image 4 - Label: 0
Image 5 - Label: 1
Image 6 - Label: 0
Image 7 - Label: 1
Image 8 - Label: 2
Image 1 - Label: 2
Image 2 - Label: 1
Image 3 - Label: 2
Image 4 - Label: 0
Image 5 - Label: 2
Image 6 - Label: 2
Image 7 - Label: 0
Image 8 - Label: 0
Image 1 - Label: 0
Image 2 - Label: 0
Image 3 - Label: 1
Image 4 - Label: 0
Image 5 - Label: 0
Image 6 - Label: 1
Image 7 - Label: 0
Image 8 - Label: 1
Image 1 - Label: 2
Image 2 - Label: 1
Image 3 - Label: 0
Image 4 - Label: 1
Image 5 - Label: 1
Image 6 - Label: 1
Image 7 - Label: 0
Image 8 - Label: 0


In [11]:
print_dataset_examples(train_dataset, class_names)
print_dataset_examples(test_dataset, class_names)

Image batch shape: (10, 192, 192, 3)
Dataset Examples (Flattened images and labels):
          0         1         2         3         4         5         6  \
0  0.647059  0.647059  0.647059  0.623529  0.623529  0.623529  0.517647   
1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.705882  0.705882  0.705882  0.701961  0.701961  0.701961  0.698039   

          7         8         9  ...    110583    110584    110585    110586  \
0  0.517647  0.517647  0.403922  ...  0.235294  0.235294  0.235294  0.282353   
1  0.000000  0.000000  0.000000  ...  0.427451  0.427451  0.427451  0.490196   
2  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.000000  ...  0.101961  0.101961  0.101961  0.058824   
4  0.698039  0.698039  0.701961  ...  0.239216  0.239216  0.2392

In [35]:
print(f"Classes: {class_names}")

for images, labels in train_dataset.take(1):
    print(f"Shape of train images: {images.shape}")
    print(f"Shape of train labels: {labels.shape}")
    print(f"Images type: {type(images)}")
    print(f"Labels type: {type(labels)}")
    print(f"Images dtype: {images.dtype}")
    print(f"Labels dtype: {labels.dtype}")

for images, labels in test_dataset.take(1):
    print(f"Shape of test images: {images.shape}")
    print(f"Shape of test labels: {labels.shape}")
    print(f"Images type: {type(images)}")
    print(f"Labels type: {type(labels)}")
    print(f"Images dtype: {images.dtype}")
    print(f"Labels dtype: {labels.dtype}")

Classes: ['aura', 'minere', 'montfleur']
Shape of train images: (10, 192, 192, 3)
Shape of train labels: (10,)
Images type: <class 'tensorflow.python.framework.ops.EagerTensor'>
Labels type: <class 'tensorflow.python.framework.ops.EagerTensor'>
Images dtype: <dtype: 'float32'>
Labels dtype: <dtype: 'int32'>
Shape of test images: (10, 192, 192, 3)
Shape of test labels: (10,)
Images type: <class 'tensorflow.python.framework.ops.EagerTensor'>
Labels type: <class 'tensorflow.python.framework.ops.EagerTensor'>
Images dtype: <dtype: 'float32'>
Labels dtype: <dtype: 'int32'>


In [25]:
import tensorflow as tf

# Check if TensorFlow is using a GPU
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0


In [18]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [22]:
import tensorflow as tf
from tensorflow.keras import layers, models

learning_rate = 0.0001
epochs = 8

# Build your model
model = models.Sequential([
    layers.Input(shape=(192, 192, 3)),
    layers.Conv2D(3, (1, 1), activation="linear", name="Force_Grayscale"),
    layers.Conv2D(32, (3, 3), activation="relu"),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(128, (3, 3), activation="relu"),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(256, (3, 3), activation="relu"),
    layers.MaxPooling2D(2, 2),
    layers.Flatten(),
    layers.Dropout(0.6),
    layers.Dense(3, activation="softmax")  # Make sure this matches the number of classes
])

# Compile with explicit learning rate
optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
model.compile(optimizer=optimizer, 
              loss="sparse_categorical_crossentropy", 
              metrics=["accuracy"])

model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Force_Grayscale (Conv2D)        │ (None, 192, 192, 3)    │            12 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_15 (Conv2D)              │ (None, 190, 190, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_15 (MaxPooling2D) │ (None, 95, 95, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_16 (Conv2D)              │ (None, 93, 93, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_16 (MaxPooling2D) │ (None, 46, 46, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_17 (Conv2D)              │ (None, 44, 44, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_17 (MaxPooling2D) │ (None, 22, 22, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_18 (Conv2D)              │ (None, 20, 20, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_18 (MaxPooling2D) │ (None, 10, 10, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_4 (Flatten)             │ (None, 25600)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 25600)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │        76,803 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 465,231 (1.77 MB)

 Trainable params: 465,231 (1.77 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)

history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=epochs,
    callbacks=[early_stopping]
)

model.evaluate(test_dataset)

# Save the model to a file
model.save("my_model.keras")

Epoch 1/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 125s 125ms/step - accuracy: 0.3885 - loss: 1.0810 - val_accuracy: 0.6616 - val_loss: 0.8918
Epoch 2/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 128s 129ms/step - accuracy: 0.6174 - loss: 0.8662 - val_accuracy: 0.7904 - val_loss: 0.6027
Epoch 3/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 119s 120ms/step - accuracy: 0.7107 - loss: 0.6914 - val_accuracy: 0.8169 - val_loss: 0.4731
Epoch 4/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 115s 116ms/step - accuracy: 0.7751 - loss: 0.5704 - val_accuracy: 0.8371 - val_loss: 0.4020
Epoch 5/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 120s 121ms/step - accuracy: 0.8072 - loss: 0.4930 - val_accuracy: 0.8712 - val_loss: 0.3497
Epoch 6/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 125s 126ms/step - accuracy: 0.8404 - loss: 0.4184 - val_accuracy: 0.9066 - val_loss: 0.2669
Epoch 7/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 124s 125ms/step - accuracy: 0.8658 - loss: 0.3578 - val_accuracy: 0.9217 - val_loss: 0.2315
Epoch 8/8
990/990 ━━━━━━━━━━━━━━━━━━━━ 123s 124ms/step - accuracy: 0.8867 - loss: 0

In [30]:
model = keras.models.load_model("my_model.keras")

In [24]:
import tensorflow as tf
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# Assuming you have already trained your model and have the test_dataset ready
# Make predictions on the test dataset
y_true = []
y_pred = []

# Iterate over the test dataset and make predictions
for step, (images, labels) in enumerate(test_dataset):
    print(f"Step {step+1}: Processing batch")

    # True labels (ground truth)
    y_true.extend(labels.numpy())
    print(f"True labels (y_true): {labels.numpy()}")

    # Model predictions
    predictions = model(images, training=False)
    print(f"Model predictions (raw): {predictions.numpy()}")

    # Get the class with the highest score
    predicted_labels = tf.argmax(predictions, axis=-1)
    print(f"Predicted labels (argmax): {predicted_labels.numpy()}")

    # Store predicted labels
    y_pred.extend(predicted_labels.numpy())

# Calculate Precision, Recall, and F1 score using sklearn
precision = precision_score(y_true, y_pred, average='macro')  # Use 'micro', 'macro', or 'weighted' depending on your needs
recall = recall_score(y_true, y_pred, average='macro')  # Use 'micro', 'macro', or 'weighted' depending on your needs
f1 = f1_score(y_true, y_pred, average='macro')  # Calculate F1 score

# Print the results
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")


Step 1: Processing batch
True labels (y_true): [1 2 1 2 1 1 0 1]
Model predictions (raw): [[1.7230275e-01 7.9171073e-01 3.5986561e-02]
 [2.3894945e-04 2.6364075e-03 9.9712461e-01]
 [7.6284289e-04 9.9884355e-01 3.9357087e-04]
 [1.3903720e-02 1.9887578e-02 9.6620864e-01]
 [2.3225318e-04 9.9383634e-01 5.9313364e-03]
 [5.4613495e-04 9.9867189e-01 7.8196172e-04]
 [9.7638547e-01 2.1435356e-02 2.1791079e-03]
 [7.8771755e-02 5.0320733e-01 4.1802084e-01]]
Predicted labels (argmax): [1 2 1 2 1 1 0 1]
Step 2: Processing batch
True labels (y_true): [0 1 0 2 0 2 1 2]
Model predictions (raw): [[9.9861348e-01 1.3837907e-03 2.6994694e-06]
 [5.4941128e-04 9.9945003e-01 6.1528482e-07]
 [7.7320856e-01 1.5989593e-01 6.6895463e-02]
 [1.0263765e-02 5.8289464e-03 9.8390722e-01]
 [9.9974042e-01 2.4690700e-04 1.2612705e-05]
 [1.4678559e-02 3.0912636e-03 9.8223019e-01]
 [1.3745753e-02 8.0868369e-01 1.7757055e-01]
 [1.8673415e-01 3.0605111e-01 5.0721478e-01]]
Predicted labels (argmax): [0 1 0 2 0 2 1 2]
Step 3: 